// example/car-web-react/src/components/common/Pagination.js
import React, {Component} from 'react';

export default class Pagination extends Component {

    constructor(props) {
        super(props);
        this.state = {
            curIndex: 1
        }
    }

    forward() {

        let {curIndex} = this.state;
        if (curIndex > 1) {
            this.setState({
                ...this.state,
                curIndex: curIndex - 1
            })
            const {switchHandle} = this.props;
            switchHandle instanceof Function && switchHandle(curIndex - 1);
        }

    }

    next() {

        let {curIndex} = this.state;
        let {amount} = this.props;
        if (curIndex < amount) {
            this.setState({
                ...this.state,
                curIndex: curIndex + 1
            })

            const {switchHandle} = this.props;
            switchHandle instanceof Function && switchHandle(curIndex + 1);
        }


    }

    switch(index) {
        if (index !== this.state.curIndex) {
            this.setState(
                {
                    ...this.state,
                    curIndex: index
                }
            )

            const {switchHandle} = this.props;
            switchHandle instanceof Function && switchHandle(index);

        }

    }

    render() {

        const {amount = 1} = this.props;
        const {curIndex} = this.state;


        return (
            <ul className="pagination">
                <li onClick={this.forward.bind(this)}>
                    <a href="#">
                        <span>&laquo;</span>
                    </a>
                </li>
                {new Array(amount).fill(1).map((v, i) => (
                    <li key={i} className={curIndex === i + 1 ? 'active' : ''} onClick={this.switch.bind(this, i + 1)}>
                        <a
                            href="#">{i + 1}</a></li>))}
                <li onClick={this.next.bind(this)}>
                    <a href="#">
                        <span>&raquo;</span>
                    </a>
                </li>
            </ul>

        )
    }

}

// example/car-web/src/components/common/Pagination.vue
<template>
    <nav>
        <ul class="pagination">
            <li @click="forward">
                <a href="#">
                    <span>&laquo;</span>
                </a>
            </li>
            <li v-for="index in amount" @click="change(index)" :class="{active:cur===index}"><a href="#">{{index}}</a>
            </li>
            <li @click="next">
                <a href="#">
                    <span>&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</template>

<script>
    export default {
        name: "Pagination",
        props: {
            amount: {
                type: Number,
                default: 0
            }
        },
        data() {
            return {
                cur: 1
            }
        },
        methods: {
            change(index) {
                if (this.cur !== index) {
                    this.cur = index;
                    this.$emit('pagination', index);
                }
            },
            forward() {
                if (this.cur > 1) {
                    this.cur--;
                    this.$emit('pagination', this.cur);
                }

            },
            next() {
                if (this.cur < this.amount) {
                    this.cur++;
                    this.$emit('pagination', this.cur);
                }

            }
        }
    }
</script>

<style scoped>

</style>
