// example/car-web-react/src/components/admin/Login.js
import React, {Component} from 'react';
import withNet from "../common/Net";
import {connect} from 'react-redux';
import {setToken} from "../../store/admin/actions";

class Login extends Component {


    constructor(props) {
        super(props);
        this.usernameRef = React.createRef();
        this.passwordRef = React.createRef();
    }

    login() {

        let username = this.usernameRef.current.value;
        let password = this.passwordRef.current.value;
        this.props.post('/login', {username, password}).then(({err, token}) => {
            if (err) alert('账户或密码错误！');
            else {
                this.props.history.push('/index/banner');
                this.props.setToken({token});
            }
        })


    }

    render() {

        return (
            <div>
                <div className="dialog-shadow"/>
                <div className="panel panel-default dialog-panel">
                    <div className="panel-heading">
                        <h2 className="panel-title">
                            登录
                            {/*<a href="#" className="glyphicon glyphicon-remove pull-right"/>*/}
                        </h2>
                    </div>
                    <div className="panel-body">
                        {/*内容*/}
                        <form>
                            <div className="form-group">
                                <label htmlFor="username">用户名</label>
                                <input type="text" className="form-control" id="username" name="username"
                                       placeholder="请输入用户名" ref={this.usernameRef}/>
                            </div>
                            <div className="form-group">
                                <label htmlFor="password">密码</label>
                                <input type="password" className="form-control" id="password" name="username"
                                       placeholder="请输入用户名" ref={this.passwordRef}/>
                            </div>
                            <div className="form-group">
                                <button type="button" className="btn btn-primary" onClick={this.login.bind(this)}>登录
                                </button>
                                {/*<button type="button" className="btn btn-default">取消</button>*/}
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        )
    }

}

export default connect((state, props) => props, {
    setToken
})(withNet(Login));

// example/car-web/src/components/admin/Login.vue
<template>
    <div>
        <div class="dialog-shadow"></div>
        <div class="panel panel-default dialog-panel">
            <div class="panel-heading">
                <h2 class="panel-title">
                    登录
                    <!--                    <a href="#" class="glyphicon glyphicon-remove pull-right"></a>-->
                </h2>
            </div>
            <div class="panel-body">
                <!--内容-->
                <form>
                    <div class="form-group">
                        <label for="username">用户名</label>
                        <input v-model="username" @focus="hasError = false" type="text" class="form-control"
                               id="username" name="username"
                               placeholder="请输入用户名">
                    </div>
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input v-model="password" @focus="hasError= false" type="password" class="form-control"
                               id="password" name="username"
                               placeholder="请输入用户名">
                    </div>
                    <div v-if="hasError" class="alert alert-danger">账户或密码错误</div>
                    <div class="form-group buttons">
                        <button type="button" class="btn btn-primary" @click="submit">登录</button>
                        <!--                        <button type="button" class="btn btn-default">取消</button>-->
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>

<script>
    import {mapActions} from 'vuex';

    export default {
        name: "login",
        data() {
            return {
                username: null,
                password: null,
                hasError: false
            }
        },
        methods: {
            ...mapActions('admin', ['login']),
            submit() {
                this.login({
                    username: this.username,
                    password: this.password
                }).then(res => {
                    //todo...
                    console.log(res);
                    this.$router.push('/admin');
                }).catch(e => this.hasError = true);
            }
        }
    }
</script>

<style scoped>
    .dialog-panel {
        position: fixed;
        left: 50%;
        top: 200px;
        width: 500px;
        margin-left: -250px;
        z-index: 99;
    }

    .dialog-shadow {
        position: fixed;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.3;
        z-index: 98;
    }

    .buttons {
        text-align: center;
    }

</style>
